services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql

  akaunting:
    image: akaunting/akaunting:latest
    container_name: akaunting
    environment:
      AKAUNTING_SETUP: "true"
      APP_ENV: "production"
      APP_LOCALE: "en-GB"
      APP_INSTALLED: "false"
      APP_DEBUG: "true"
      DB_CONNECTION: "mysql"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      MYSQL_DATABASE: ${MYSQL_DATABASE} #database name
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      COMPANY_NAME: ${COMPANY_NAME}
      COMPANY_EMAIL: ${COMPANY_EMAIL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - ./logs:/var/log
      - ./config:/var/www/akaunting/config
      - ./storage:/var/www/html/storage
      - ./modules:/var/www/html/modules
